<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{{ asset('_next/static/css/35589db532007dfe2.css') }}">
<link rel="stylesheet" href="{{ asset('_next/static/css/45110fd9899fdfe2.css') }}">
<link rel="stylesheet" href="{{ route('theme.css') }}">
<title>برامج ريادة الأعمال | بيزه للخدمات المالية</title>
<meta name="description" content="نرعى الشركات الناشئة ونمكّن رواد الأعمال من تحقيق أحلامهم">
<link rel="icon" href="{{ asset('biza-logo.png') }}">
</head>
<body class="min-h-screen bg-white">
<nav class="fixed top-0 left-0 right-0 z-50 transition-all duration-500 bg-transparent">
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="flex items-center justify-between h-20">
<a class="flex items-center gap-3 group" href="{{ route('home') }}"><div class="relative w-14 h-14 transition-transform duration-300 group-hover:scale-110"><img alt="Biza Logo" class="object-contain w-full h-full" src="{{ asset('biza-logo.webp') }}"></div><span class="text-2xl font-bold transition-colors duration-300 text-white">بيزه</span></a>
<div class="hidden lg:flex items-center gap-0.5"><a class="px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 text-white/90 hover:text-white hover:bg-white/10" href="{{ route('home') }}">الرئيسية</a><a class="px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 text-white/90 hover:text-white hover:bg-white/10" href="{{ route('about') }}">من نحن</a><a class="px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 text-white/90 hover:text-white hover:bg-white/10" href="{{ url('/entrepreneurship') }}">برامج ريادة الأعمال</a><a class="px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 text-white/90 hover:text-white hover:bg-white/10" href="{{ route('legacy.page', 'contact') }}">تواصل معنا</a></div>
<div class="hidden lg:flex items-center gap-3"><a class="btn-secondary text-sm py-2.5 px-5" href="{{ route('legacy.page', 'contact') }}">احصل على استشارة</a></div>
</div></div></nav>
<main>
<section class="relative pt-32 pb-20 bg-gradient-to-br from-biza-green via-biza-green-dark to-slate-900 overflow-hidden"><div class="absolute inset-0 pattern-grid opacity-20"></div><div class="absolute top-20 start-10 w-72 h-72 bg-white/5 rounded-full blur-3xl"></div><div class="absolute bottom-20 end-10 w-96 h-96 bg-biza-yellow/10 rounded-full blur-3xl"></div><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative"><div class="grid lg:grid-cols-2 gap-12 items-center"><div><span class="inline-block px-4 py-2 bg-white/10 text-white rounded-full text-sm font-semibold mb-6">برامج ريادة الأعمال</span><h1 class="heading-1 text-white mb-6">برامج ريادة الأعمال</h1><p class="text-xl text-white/80 mb-8">نرعى الشركات الناشئة ونمكّن رواد الأعمال من تحقيق أحلامهم</p><a href="{{ route('legacy.page', 'contact') }}" class="btn-secondary inline-flex items-center gap-2">احصل على استشارة</a></div><div class="hidden lg:block relative"><div class="relative w-80 h-80 mx-auto"><div class="absolute inset-0 bg-white/10 rounded-full animate-pulse-slow"></div><img src="{{ asset('biza-coin-glod.png') }}" alt="Entrepreneurship" class="object-contain relative w-full h-full"></div></div></div></div></section>
<section class="section-padding bg-white"><div class="max-w-4xl mx-auto text-center"><p class="text-xl text-gray-600 leading-relaxed">نوفر الإرشاد والتدريب وفرص التمويل المصممة لرعاية الشركات الناشئة ورواد الأعمال، وبناء نظام بيئي حيوي ومستدام للأعمال</p></div></section>
<section class="section-padding bg-gray-50"><div class="max-w-7xl mx-auto"><div class="text-center mb-16"><h2 class="heading-2 text-gray-900">رحلتك معنا</h2></div><div class="grid md:grid-cols-4 gap-6">@foreach ([['title'=>'تقييم الفكرة','desc'=>'نقيم فكرتك ونساعدك في تطويرها'],['title'=>'الإرشاد والتوجيه','desc'=>'نوفر لك مرشدين خبراء في مجالك'],['title'=>'التدريب','desc'=>'نقدم برامج تدريبية متخصصة'],['title'=>'الإطلاق','desc'=>'نساعدك في إطلاق مشروعك بنجاح']] as $i => $step)<div class="bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition-shadow text-center"><div class="w-16 h-16 bg-gradient-to-br from-biza-green to-biza-green-dark rounded-2xl flex items-center justify-center mx-auto mb-6"><span class="text-3xl text-white">{{ $i + 1 }}</span></div><h3 class="text-xl font-bold text-gray-900 mb-2">{{ $step['title'] }}</h3><p class="text-gray-600">{{ $step['desc'] }}</p></div>@endforeach</div></div></section>
<section class="section-padding bg-white"><div class="max-w-7xl mx-auto"><div class="text-center mb-16"><h2 class="heading-2 text-gray-900">خدمات ريادة الأعمال</h2></div><div class="grid md:grid-cols-2 gap-8">@foreach ([['title'=>'الإرشاد والتوجيه','desc'=>'برامج إرشاد متخصصة مع خبراء في مجالات متعددة'],['title'=>'التدريب والتأهيل','desc'=>'ورش عمل ودورات تدريبية لتطوير المهارات الريادية'],['title'=>'دعم التمويل','desc'=>'المساعدة في الوصول إلى مصادر التمويل والمستثمرين'],['title'=>'حاضنات الأعمال','desc'=>'بيئة داعمة لنمو المشاريع الناشئة وتطويرها']] as $service)<article class="group bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition-all duration-500 hover:-translate-y-2 border border-gray-100"><div class="w-16 h-16 rounded-2xl bg-gradient-to-br from-biza-green to-biza-green-dark flex items-center justify-center mb-6"><span class="text-2xl text-white">✦</span></div><h3 class="text-2xl font-bold text-gray-900 mb-4">{{ $service['title'] }}</h3><p class="text-gray-600 leading-relaxed">{{ $service['desc'] }}</p></article>@endforeach</div></div></section>
<section class="section-padding bg-gradient-to-br from-biza-green to-biza-green-dark text-white"><div class="max-w-7xl mx-auto"><div class="grid md:grid-cols-4 gap-8 text-center">@foreach ([['50+','شركة ناشئة'],['30+','مرشد خبير'],['5M+','تمويل محصل'],['90%','نسبة النجاح']] as $stat)<div><div class="text-5xl font-bold mb-2">{{ $stat[0] }}</div><div class="text-white/70">{{ $stat[1] }}</div></div>@endforeach</div></div></section>
<section class="section-padding relative overflow-hidden"><div class="absolute inset-0 hero-gradient"></div><div class="absolute inset-0 pattern-dots opacity-30"></div><div class="max-w-4xl mx-auto relative text-center"><h2 class="text-4xl md:text-5xl lg:text-6xl font-black text-white leading-tight mb-6">هل أنت مستعد لتحويل أعمالك؟</h2><p class="text-lg text-white/70 mb-12">تواصل معنا اليوم واحصل على استشارة مجانية</p><a class="btn-secondary inline-flex items-center gap-2.5 text-base" href="{{ route('legacy.page', 'contact') }}">احجز استشارتك المجانية</a></div></section>
</main>
<footer class="bg-gradient-to-br from-gray-950 via-gray-900 to-gray-950 text-white"><div class="h-1 bg-gradient-to-r from-biza-green via-biza-yellow to-biza-green"></div><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16"><div class="text-center"><img class="w-16 h-16 object-contain mx-auto mb-4" src="{{ asset('biza-logo.webp') }}"><span class="text-2xl font-bold">بيزه</span><p class="text-gray-400 mt-4">شركة عمانية متخصصة في تقديم الاستشارات المالية والاقتصادية.</p></div></div><div class="border-t border-white/10 text-center py-6 text-gray-400 text-sm">© {{ date('Y') }} بيزه للخدمات المالية. جميع الحقوق محفوظة.</div></footer>
</body></html>
